package com.stefan.poslovnabanka.enums;

public enum TipGreske {
    IZVRSEN_NALOG,
    NEIZVRSEN_ZBOG_NELIKVIDNOSTI_PODRACUNA_KORISNIKA,
    NEIZVRSEN_ZBOG_NELIKVIDNOSTI_RACUNA_NOSIOCA_U_NBJ,
    POGRESAN_NALOG,
    NALOG_STOPIRAN_ZA_IZVRSENJE
}
